#!/bin/bash
READLINK=readlink
which greadlink && READLINK=greadlink
pluginpath="$(dirname "$($READLINK -f $0)")"

ln -svf $pluginpath/gitconfig "$HOME/.gitconfig"

mkdir -p $HOME/dev/{src,c,js,rust,go}

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

git clone https://github.com/tfutils/tfenv.git ~/.tfenv
git clone https://github.com/cunymatthieu/tgenv.git ~/.tgenv

pip install lice  # a license generation tool
cargo install fnm # node.js version manager

eval $(fnm env) # enable node.js
fnm install --lts

npm config set prefix $HOME/npm
npm -g install json clocker http-console2

echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
  sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
  sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

sudo apt-get update && sudo apt-get install google-cloud-cli kubectl
